name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy_lambda:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            with:
                node-version: '14'
